### PR TITLE
Prepare release 7.17.5.0

### PR DESCRIPTION
**Pull request by nicenatalia**

### CODE REVIEW

**Comment by nicenatalia** [comment]
@benj-moreau @baptabl 
Hi there! Please review this PR at your earliest convenience. Elasticsearch released a fix for the fvh highlighter in 7.17.5 and our project needs this plugin to work with that version.

Thanks in advance and for all the work done to keep this plugin alive!

**Comment by mhugo** [comment]
@nicenatalia Hi, thanks for your contribution. But isn't the current 7.17.1.0 plugin compliant with ES 7.17.5 ? I would assume plugins should work whatever the bugfix version of an ES release version. I admit this is kind of confusing. @benj-moreau @baptabl Maybe we can change the version schema to only keep the two first numbers from ES (7.17 here) and add one number for the plugin version ?

**Comment by nicenatalia** [comment]
Hi @mhugo, I also thought the current 7.17.1.1 release was going to work with ES 7.17.5 but I'm seeing this error during installation: 
**Plugin [pathhierarchy-aggregation] was built for Elasticsearch version 7.17.1 but version 7.17.5 is running**


`$ sudo ./elasticsearch-plugin install https://github.com/opendatasoft/elasticsearch-aggregation-pathhierarchy/releases/download/v7.17.1.1/pathhierarchy-aggregation-7.17.1.1.zip
-> Installing https://github.com/opendatasoft/elasticsearch-aggregation-pathhierarchy/releases/download/v7.17.1.1/pathhierarchy-aggregation-7.17.1.1.zip
-> Downloading https://github.com/opendatasoft/elasticsearch-aggregation-pathhierarchy/releases/download/v7.17.1.1/pathhierarchy-aggregation-7.17.1.1.zip
[=================================================] 100%   
-> Failed installing https://github.com/opendatasoft/elasticsearch-aggregation-pathhierarchy/releases/download/v7.17.1.1/pathhierarchy-aggregation-7.17.1.1.zip
-> Rolling back https://github.com/opendatasoft/elasticsearch-aggregation-pathhierarchy/releases/download/v7.17.1.1/pathhierarchy-aggregation-7.17.1.1.zip
-> Rolled back https://github.com/opendatasoft/elasticsearch-aggregation-pathhierarchy/releases/download/v7.17.1.1/pathhierarchy-aggregation-7.17.1.1.zip
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [pathhierarchy-aggregation] was built for Elasticsearch version 7.17.1 but version 7.17.5 is running
	at org.elasticsearch.plugins.PluginsService.verifyCompatibility(PluginsService.java:391)
	at org.elasticsearch.plugins.cli.InstallPluginAction.loadPluginInfo(InstallPluginAction.java:831)
	at org.elasticsearch.plugins.cli.InstallPluginAction.installPlugin(InstallPluginAction.java:887)
	at org.elasticsearch.plugins.cli.InstallPluginAction.execute(InstallPluginAction.java:245)
	at org.elasticsearch.plugins.cli.InstallPluginCommand.execute(InstallPluginCommand.java:88)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:95)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
	at org.elasticsearch.cli.Command.main(Command.java:77)
	at org.elasticsearch.plugins.cli.PluginCli.main(PluginCli.java:36)
`

**Comment by nicenatalia** [comment]
Sorry for being a little pushy but would it be possible for you guys to review the PR this week?

**Comment by mhugo** [comment]
Sorry for the delay, we will add a 7.17.5.0 release very soon

**Comment by benj-moreau** [comment]
Hi @nicenatalia, thanks for your contribution. Lets merge this PR and realease 7.17.5.0 !

**Comment by nicenatalia** [comment]
Thank you very much @mhugo and @benj-moreau!!

**Comment by benj-moreau** [comment]
You're welcome @nicenatalia.  7.17.5.0 is now released. I let you try it and come back to us if you have any problem with it.

**Pull request merged**
